### ISSUE TITLE
Validate requestBody and maybe header.

### ISSUE THREAD

**Issue by Nitwel** [RuntimeTools/OpenAPIValidators#147]
**OpenAPI version**
Any

**Describe the solution you'd like**
It would be real nice to support matching the request against everything in the specs.
Currently, only the response gets checked and not the request header / request body and so on.

Yes, in theory these should always match the spec by default but for the case that an api gets an update so you update the test but forget to update the specs, you won't get a notification currently. And I know that would be working in the wrong way but still it would be a really nice feature. 

**Are you going to resolve the issue?**
I will definitely look into that!

**Comment by rwalle61** [comment]
Thanks for this @Nitwel!

May I ask you to clarify how you would like this feature to be used: 
- Would it run in the test code or server code
- How would the assertion read?

I agree this is a useful feature, but as it validates the request not the response, how does it fit with the mission of this project? (I'm not saying it doesn't, I am just encouraging you to clarify :) )

**Comment by Nitwel** [comment]
Sure do.
I'm currently sometimes running into the issue that when I update the object that is send to the api, I forget to update these chanes inside the openapi spec which causes confusion. So checking the request too would help resolve inconsistencies between the spec and the tests.

This would also apply to chanes made in the spec which where forgotten to update inside the tests.

Here's an example:
Our `/auth/refresh` endpoint got recently updated to require `{refresh_token: token}` where it was `{token: token}` before.
I updated the tests to match the updated endpoint but forgot to update the requestBody in the specs which caused a bit of confusion.

So adding this would just make the specs even more consistent with the tests.

**Comment by rwalle61** [comment]
Thanks, I have had this issue myself where I want to ensure that my _Request_ and API spec match. Usually in Express server apps I solve it using this custom middleware: https://github.com/eclipse/codewind/blob/master/src/pfe/portal/middleware/reqValidator.js

I have considered publishing that pattern as another npm package actually, but I haven't because there may already be some packages that do the same thing (I can't remember if there are)

So you could use that to solve your problem. 

I think ensuring that the _Request_ satisfies the API spec is different to this package's current purpose, which is to ensure that the _Response_ satisfies the API spec. 

That said, I'm open to expanding this package's purpose slightly if users want it. I suppose you might want to write a test like: 
```
const request = ...
expect(request).toSatisfyApiSpec()

const response = await makeRequest(request)

expect(response).toSatisfyApiSpec()
```

However an alternate way to ensure the request satisfies the API spec would be to use the middleware I linked above, and test those 4xx error cases.

What do you think?

**Comment by Nitwel** [comment]
I think the best solution for me would be to either fork this project and add that feature there or if you think it is inside the scope of the project to add that feature here.

I get that you see this project only as an response validator but the way I understood this project was that you can easily validate the the whole specs against an api.

**Comment by rwalle61** [comment]
In that case I'd be happy for you to implement the feature you want on your fork, and we can look at whether to merge it in or not at that point :)

**Comment by rwalle61** [comment]
@Nitwel out of curiousity, did you ever implement this?

I'll close this for now but we can keep reopen / keep discussing as necessary

**Comment by Nitwel** [comment]
My priorities shifted to other things so I had no time to work on this. If we ever need this feature I'll happily create a PR but for now there is to much other stuff to do.

**Comment by michaelgwelch** [comment]
Was just coming here to look for this feature. Are use case is that we want to make sure that what we documented as our request schema actually matches what we use for requests.
