### ISSUE TITLE
Support for schema in multiple files

### ISSUE THREAD

**Issue by dalogax** [RuntimeTools/OpenAPIValidators#45]
I'am having trouble with my schema that is separated in more than one file because is too large.
The error is:
`Uncaught AssertionError: expected res to satisfy API spec:
{ message: 'The response was not valid.',
  errors:
   [ { path: 'xmedia[0]',
       errorCode: '$ref.openapi.responseValidation',
       message:
        'Pet[0] can\'t resolve reference ./schemas/common/Pet.yml' },`
And my file directory is something like this:
- api_spec.yml
- schemas
  - common
    - Pet.yml

**Comment by rwalle61** [comment]
Hi @dalogax, thanks for raising this. We do not currently support this feature, but it is a legitimate use case so I'm happy for you/me/someone to implement this!

### Initial thoughts on how one might do this:
Currently, we assume that the OpenAPI spec file the user loads contains the schemas as well. Thus we access schemas by simply calling [`this.spec.definitions` for OpenAPI 2 specs](https://github.com/RuntimeTools/chai-openapi-response-validator/blob/master/lib/classes/OpenApi2Spec.js) and [`this.spec.components` for OpenAPI 3 specs](https://github.com/RuntimeTools/chai-openapi-response-validator/blob/master/lib/classes/OpenApi3Spec.js#L99).

When the user first loads the spec, we could scan the spec to find references to schemas in other files, then add them to `this.spec.definitions` or `this.spec.components`.

The benefits of this are that:
- with just this change, the `getComponentDefinitions` methods (and everything else) may just work. 
- we will look in other files just once (rather than every time we want to access definitions)
- by looking in other files at the start, we can warn the user early on if the other files don't exist or are invalid

A potential drawback of looking for schemas just once (on the first load) is if in future we want to support references to schemas accessed on web endpoints. In that case, if we access those schemas only on the first load, then we will be out of date if somehow they change. That is quite a niche use case though, so I think we're fine

Would this work in your example? (I've never personally used separate OpenAPI files before)

**Comment by rwalle61** [comment]
Fyi I realised that using multiple openapi files is a common practice, and so someone must have made a tool to combine them already. I found 3 that might help:
- `json-refs` (see https://azimi.me/2015/07/16/split-swagger-into-smaller-files.html and https://github.com/whitlockjc/json-refs/blob/master/docs/API.md#module_json-refs.resolveRefs)
- [`json-schema-ref-parser`](https://github.com/APIDevTools/json-schema-ref-parser) (api docs: https://apitools.dev/json-schema-ref-parser/docs/)
- [`speccy`](https://github.com/wework/speccy#calling-speccy-from-code)

The problem with these methods is that they are asynchronous - they all return promises or callbacks. If we use them in this package, then everyone using this package will have to load their api specs asynchronously, i.e. instead of doing this:
```js
// setup
chai.use(chaiResponseValidator(pathToApiSpec));
// tests
```
everyone will have to do this:
```js
// setup
// describe(...
before(function () {
    chai.use(chaiResponseValidator(pathToApiSpec));
});
// tests
```

Breaking everyone who uses this package the first way is a major problem. However, there are several benefits to loading asynchronously:
- ability to support multi-file schemas (this issue)
- ability to load schemas from URLs (https://github.com/RuntimeTools/chai-openapi-response-validator/issues/31)
- ability to load different api specs for different tests (https://github.com/RuntimeTools/chai-openapi-response-validator/issues/44)

There are different pros and cons for loading sync vs async. Maybe there is a way to export both sync and async versions so that users can choose. Or if that would be too complex to maintain then we should decide whether we will proceed with sync or async

**Comment by rwalle61** [comment]
Closing as there doesn't seem to be a way currently to combine schemas in multiple files *synchronously*. Feel free to reopen if you have an idea!
